### ISSUE TITLE
程序报错，跑不起来

### ISSUE THREAD

**Issue by chaozhankai** [xiaoxu97/mirai-plus#4]
install了mirai-plus-pom，填写了QQ号，修改了TalkHandler，运行时报错。感觉也不像是我的问题啊，是的话我又哪会解决掉呢。急死孩子了，明天开盘了。
以下是运行时的相关信息
=====================================================================
2020-12-27 20:20:30.395  INFO 16100 --- [           main] c.z.miraiplus.MiraiPlusApplication       : Starting MiraiPlusApplication on DESKTOP-NMMVULK with PID 16100 (D:\My Project\IDEA-project\mirai-plus\mirai-plus-demo\target\classes started by Administrator in D:\My Project\IDEA-project\mirai-plus)
2020-12-27 20:20:30.396  INFO 16100 --- [           main] c.z.miraiplus.MiraiPlusApplication       : No active profile set, falling back to default profiles: default
2020-12-27 20:20:31.064  INFO 16100 --- [           main] c.z.miraiplus.MiraiPlusApplication       : Started MiraiPlusApplication in 0.898 seconds (JVM running for 1.545)
2020-12-27 20:20:32.077  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : Logging in...
2020-12-27 20:20:32.133  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : Connected to server 42.81.169.46:8080
2020-12-27 20:20:32.653  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : Login successful
2020-12-27 20:20:32.820  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : 开始加载好友信息
2020-12-27 20:20:32.825  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : 开始加载群组列表与群成员列表
2020-12-27 20:20:32.962  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : 好友列表加载完成, 共 13个
2020-12-27 20:20:34.450  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : 群组列表与群成员加载完成, 共 8个
2020-12-27 20:20:34.450  INFO 16100 --- [atcher-worker-3] c.z.miraiplus.component.MiraiPlusLog     : Awaiting ConfigPushSvc.PushReq
2020-12-27 20:20:34.450  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : Syncing friend message history...
2020-12-27 20:20:34.930  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : Syncing friend message history: Success
2020-12-27 20:20:34.930  INFO 16100 --- [           main] c.z.miraiplus.component.MiraiPlusLog     : Login successful
2020-12-27 20:20:34.931  INFO 16100 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-12-27 20:20:34.938 ERROR 16100 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at com.zhuangxv.miraiplus.MiraiPlusApplication.main(MiraiPlusApplication.java:15) [classes/:na]
Caused by: java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:277) ~[na:1.8.0_261]
	at com.zhuangxv.miraiplus.component.MiraiPlusInit.lambda$run$0(MiraiPlusInit.java:50) ~[classes/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_261]
	at com.zhuangxv.miraiplus.component.MiraiPlusInit.run(MiraiPlusInit.java:38) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	... 5 common frames omitted

2020-12-27 20:20:34.940  INFO 16100 --- [           main] c.z.m.u.MiraiPlusApplicationBeanContext  : clear ApplicationContext:org.springframework.context.annotation.AnnotationConfigApplicationContext@510f3d34, started on Sun Dec 27 20:20:30 CST 2020

Process finished with exit code 1

**Comment by xiaoxu97** [comment]
文档有说配置设备信息文件保存路径
